### PR TITLE
feat(signOut) Implementing signOut on iOS

### PR DESCRIPTION
**Pull request by Gabriel-Azevedo**
## What
Implementing signOut on iOS

## Why
As discussed on #34, signOut on iOS was missing

## How
Following the [documentation](https://support.iterable.com/hc/en-us/articles/360035031532-User-Update-Recommendations-#user-logout-and-endpointenabled)

### CODE REVIEW

**Review by danielgomezrico — APPROVED** [review]
Thanks for the feature! You also updated the docs, awesome!

**Review by cdmunoz — APPROVED** [review]
LGTM! 💯

**Comment by danielgomezrico** [comment]
It looks like we have an issue on CI, lets wait a little to merge this until it is fixed, related to:
https://github.com/la-haus/iterable-flutter/pull/38

**Comment by danielgomezrico** [comment]
@Gabriel-Azevedo please do a rebase with master to see if CI works fine to merge it :)

**Pull request merged**
